services:
  postgres:
    image: postgres:15-alpine
    container_name: notificahub-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=notificahub